# 📊 Dataset Description: Retail Sales Analysis

#### This dataset contains transactional retail sales data, capturing customer purchases across different product categories along with demographic and pricing details.
### Column Names:-
#### transactions_id, sale_date, sale_time, customer_id, gender, age, category, quantity, price_per_unit, cogs, total_sale

## End-to-End Mini Project

### 👉 Perform full EDA:

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("SQL_Sale.csv")
df

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantiy,price_per_unit,cogs,total_sale
0,180,2022-11-05,10:47:00,117,Male,41.0,Clothing,3.0,300.0,129.0,900.0
1,522,2022-07-09,11:00:00,52,Male,46.0,Beauty,3.0,500.0,145.0,1500.0
2,559,2022-12-12,10:48:00,5,Female,40.0,Clothing,4.0,300.0,84.0,1200.0
3,1180,2022-01-06,08:53:00,85,Male,41.0,Clothing,3.0,300.0,129.0,900.0
4,1522,2022-11-14,08:35:00,48,Male,46.0,Beauty,3.0,500.0,235.0,1500.0
...,...,...,...,...,...,...,...,...,...,...,...
1995,1857,2022-11-09,12:15:00,109,Male,60.0,Electronics,2.0,25.0,7.5,50.0
1996,211,2022-09-12,14:02:00,54,Male,42.0,Beauty,3.0,500.0,235.0,1500.0
1997,650,2023-10-08,12:41:00,98,Male,55.0,Electronics,1.0,30.0,15.0,30.0
1998,1211,2023-11-22,14:59:00,82,Male,42.0,Beauty,3.0,500.0,235.0,1500.0
1999,1650,2022-09-23,16:24:00,89,Male,55.0,Electronics,1.0,30.0,10.8,30.0

In [3]:
df.head()

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantiy,price_per_unit,cogs,total_sale
0,180,2022-11-05,10:47:00,117,Male,41.0,Clothing,3.0,300.0,129.0,900.0
1,522,2022-07-09,11:00:00,52,Male,46.0,Beauty,3.0,500.0,145.0,1500.0
2,559,2022-12-12,10:48:00,5,Female,40.0,Clothing,4.0,300.0,84.0,1200.0
3,1180,2022-01-06,08:53:00,85,Male,41.0,Clothing,3.0,300.0,129.0,900.0
4,1522,2022-11-14,08:35:00,48,Male,46.0,Beauty,3.0,500.0,235.0,1500.0

In [4]:
df.tail()

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantiy,price_per_unit,cogs,total_sale
1995,1857,2022-11-09,12:15:00,109,Male,60.0,Electronics,2.0,25.0,7.5,50.0
1996,211,2022-09-12,14:02:00,54,Male,42.0,Beauty,3.0,500.0,235.0,1500.0
1997,650,2023-10-08,12:41:00,98,Male,55.0,Electronics,1.0,30.0,15.0,30.0
1998,1211,2023-11-22,14:59:00,82,Male,42.0,Beauty,3.0,500.0,235.0,1500.0
1999,1650,2022-09-23,16:24:00,89,Male,55.0,Electronics,1.0,30.0,10.8,30.0

In [5]:
df.sample()

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantiy,price_per_unit,cogs,total_sale
1978,1062,2022-12-20,16:05:00,69,Male,18.0,Beauty,2.0,50.0,21.5,100.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   transactions_id  2000 non-null   int64
 1   sale_date        2000 non-null   object
 2   sale_time        2000 non-null   object
 3   customer_id      2000 non-null   int64
 4   gender           2000 non-null   object
 5   age              1990 non-null   float64
 6   category         2000 non-null   object
 7   quantiy          1997 non-null   float64
 8   price_per_unit   1997 non-null   float64
 9   cogs             1997 non-null   float64
 10  total_sale       1997 non-null   float64
dtypes: float64(5), int64(2), object(4)
memory usage: 172.0+ KB

In [7]:
df.shape

(2000, 11)

In [8]:
df.describe

<bound method NDFrame.describe of       transactions_id   sale_date sale_time  customer_id  gender   age  \
0                 180  2022-11-05  10:47:00          117    Male  41.0
1                 522  2022-07-09  11:00:00           52    Male  46.0
2                 559  2022-12-12  10:48:00            5  Female  40.0
3                1180  2022-01-06  08:53:00           85    Male  41.0
4                1522  2022-11-14  08:35:00           48    Male  46.0
...               ...         ...       ...          ...     ...   ...
1995             1857  2022-11-09  12:15:00          109    Male  60.0
1996              211  2022-09-12  14:02:00           54    Male  42.0
1997              650  2023-10-08  12:41:00           98    Male  55.0
1998             1211  2023-11-22  14:59:00           82    Male  42.0
1999             1650  2022-09-23  16:24:00           89    Male  55.0

         category  quantiy  price_per_unit   cogs  total_sale
0        Clothing      3.0           300.0  129.0       900.0
1          Beauty      3.0           500.0  145.0      1500.0
2        Clothing      4.0           300.0   84.0      1200.0
3        Clothing      3.0           300.0  129.0       900.0
4          Beauty      3.0           500.0  235.0      1500.0
...           ...      ...             ...    ...         ...
1995  Electronics      2.0            25.0    7.5        50.0
1996       Beauty      3.0           500.0  235.0      1500.0
1997  Electronics      1.0            30.0   15.0        30.0
1998       Beauty      3.0           500.0  235.0      1500.0
1999  Electronics      1.0            30.0   10.8        30.0

[2000 rows x 11 columns]>

In [9]:
df.columns

Index(['transactions_id', 'sale_date', 'sale_time', 'customer_id', 'gender',
       'age', 'category', 'quantiy', 'price_per_unit', 'cogs', 'total_sale'],
      dtype='object')

In [10]:
df.nunique

<bound method DataFrame.nunique of       transactions_id   sale_date sale_time  customer_id  gender   age  \
0                 180  2022-11-05  10:47:00          117    Male  41.0
1                 522  2022-07-09  11:00:00           52    Male  46.0
2                 559  2022-12-12  10:48:00            5  Female  40.0
3                1180  2022-01-06  08:53:00           85    Male  41.0
4                1522  2022-11-14  08:35:00           48    Male  46.0
...               ...         ...       ...          ...     ...   ...
1995             1857  2022-11-09  12:15:00          109    Male  60.0
1996              211  2022-09-12  14:02:00           54    Male  42.0
1997              650  2023-10-08  12:41:00           98    Male  55.0
1998             1211  2023-11-22  14:59:00           82    Male  42.0
1999             1650  2022-09-23  16:24:00           89    Male  55.0

         category  quantiy  price_per_unit   cogs  total_sale
0        Clothing      3.0           300.0  129.0       900.0
1          Beauty      3.0           500.0  145.0      1500.0
2        Clothing      4.0           300.0   84.0      1200.0
3        Clothing      3.0           300.0  129.0       900.0
4          Beauty      3.0           500.0  235.0      1500.0
...           ...      ...             ...    ...         ...
1995  Electronics      2.0            25.0    7.5        50.0
1996       Beauty      3.0           500.0  235.0      1500.0
1997  Electronics      1.0            30.0   15.0        30.0
1998       Beauty      3.0           500.0  235.0      1500.0
1999  Electronics      1.0            30.0   10.8        30.0

[2000 rows x 11 columns]>

# Clean missing values or null

In [11]:
df.isnull().sum()

transactions_id     0
sale_date           0
sale_time           0
customer_id         0
gender              0
age                10
category            0
quantiy             3
price_per_unit      3
cogs                3
total_sale          3
dtype: int64

In [12]:
df2=df.copy()
df2

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantiy,price_per_unit,cogs,total_sale
0,180,2022-11-05,10:47:00,117,Male,41.0,Clothing,3.0,300.0,129.0,900.0
1,522,2022-07-09,11:00:00,52,Male,46.0,Beauty,3.0,500.0,145.0,1500.0
2,559,2022-12-12,10:48:00,5,Female,40.0,Clothing,4.0,300.0,84.0,1200.0
3,1180,2022-01-06,08:53:00,85,Male,41.0,Clothing,3.0,300.0,129.0,900.0
4,1522,2022-11-14,08:35:00,48,Male,46.0,Beauty,3.0,500.0,235.0,1500.0
...,...,...,...,...,...,...,...,...,...,...,...
1995,1857,2022-11-09,12:15:00,109,Male,60.0,Electronics,2.0,25.0,7.5,50.0
1996,211,2022-09-12,14:02:00,54,Male,42.0,Beauty,3.0,500.0,235.0,1500.0
1997,650,2023-10-08,12:41:00,98,Male,55.0,Electronics,1.0,30.0,15.0,30.0
1998,1211,2023-11-22,14:59:00,82,Male,42.0,Beauty,3.0,500.0,235.0,1500.0
1999,1650,2022-09-23,16:24:00,89,Male,55.0,Electronics,1.0,30.0,10.8,30.0

In [13]:
# Correct way
df2['age'] = df2['age'].fillna(df2['age'].median())
df2
df2.isnull().sum()

transactions_id    0
sale_date          0
sale_time          0
customer_id        0
gender             0
age                0
category           0
quantiy            3
price_per_unit     3
cogs               3
total_sale         3
dtype: int64

In [14]:
column=['age','quantiy','price_per_unit','cogs','total_sale']
for col in column:
    df2[col] =df2[col].fillna(df2[col].median())
    
df2.isnull().sum()

transactions_id    0
sale_date          0
sale_time          0
customer_id        0
gender             0
age                0
category           0
quantiy            0
price_per_unit     0
cogs               0
total_sale         0
dtype: int64

# Handle duplicates

In [15]:
df2.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool

# Fix data types

In [16]:
df2['age']=df2['age'].astype(float)
df2.dtypes

transactions_id      int64
sale_date           object
sale_time           object
customer_id          int64
gender              object
age                float64
category            object
quantiy            float64
price_per_unit     float64
cogs               float64
total_sale         float64
dtype: object

In [17]:
df2.dtypes

transactions_id      int64
sale_date           object
sale_time           object
customer_id          int64
gender              object
age                float64
category            object
quantiy            float64
price_per_unit     float64
cogs               float64
total_sale         float64
dtype: object

# Create new features

# Feature Engineering

### 👉 Create:

### total_amount = quantity * price_per_unit
### A new column: "High Value" if total > 1000 else "Low Value"

In [18]:
df2.assign(total_amount = df2['quantiy'] * df2['price_per_unit'])

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantiy,price_per_unit,cogs,total_sale,total_amount
0,180,2022-11-05,10:47:00,117,Male,41.0,Clothing,3.0,300.0,129.0,900.0,900.0
1,522,2022-07-09,11:00:00,52,Male,46.0,Beauty,3.0,500.0,145.0,1500.0,1500.0
2,559,2022-12-12,10:48:00,5,Female,40.0,Clothing,4.0,300.0,84.0,1200.0,1200.0
3,1180,2022-01-06,08:53:00,85,Male,41.0,Clothing,3.0,300.0,129.0,900.0,900.0
4,1522,2022-11-14,08:35:00,48,Male,46.0,Beauty,3.0,500.0,235.0,1500.0,1500.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1857,2022-11-09,12:15:00,109,Male,60.0,Electronics,2.0,25.0,7.5,50.0,50.0
1996,211,2022-09-12,14:02:00,54,Male,42.0,Beauty,3.0,500.0,235.0,1500.0,1500.0
1997,650,2023-10-08,12:41:00,98,Male,55.0,Electronics,1.0,30.0,15.0,30.0,30.0
1998,1211,2023-11-22,14:59:00,82,Male,42.0,Beauty,3.0,500.0,235.0,1500.0,1500.0
1999,1650,2022-09-23,16:24:00,89,Male,55.0,Electronics,1.0,30.0,10.8,30.0,30.0

In [19]:
df2['value_status'] = df2['total_sale'].apply(lambda x: 'High Value' if x > 1000 else 'Low Value')
df2

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantiy,price_per_unit,cogs,total_sale,value_status
0,180,2022-11-05,10:47:00,117,Male,41.0,Clothing,3.0,300.0,129.0,900.0,Low Value
1,522,2022-07-09,11:00:00,52,Male,46.0,Beauty,3.0,500.0,145.0,1500.0,High Value
2,559,2022-12-12,10:48:00,5,Female,40.0,Clothing,4.0,300.0,84.0,1200.0,High Value
3,1180,2022-01-06,08:53:00,85,Male,41.0,Clothing,3.0,300.0,129.0,900.0,Low Value
4,1522,2022-11-14,08:35:00,48,Male,46.0,Beauty,3.0,500.0,235.0,1500.0,High Value
...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1857,2022-11-09,12:15:00,109,Male,60.0,Electronics,2.0,25.0,7.5,50.0,Low Value
1996,211,2022-09-12,14:02:00,54,Male,42.0,Beauty,3.0,500.0,235.0,1500.0,High Value
1997,650,2023-10-08,12:41:00,98,Male,55.0,Electronics,1.0,30.0,15.0,30.0,Low Value
1998,1211,2023-11-22,14:59:00,82,Male,42.0,Beauty,3.0,500.0,235.0,1500.0,High Value
1999,1650,2022-09-23,16:24:00,89,Male,55.0,Electronics,1.0,30.0,10.8,30.0,Low Value

#### 3. Customer Lifetime Value (CLV)

#### 👉 Create a feature:

#### Total money spent by each customer across all transactions

In [26]:
df2.groupby('customer_id')['total_sale'].transform('sum')

0        5200.0
1       10325.0
2       30405.0
3        8590.0
4        5870.0
         ...
1995     7680.0
1996    13475.0
1997     7535.0
1998     9360.0
1999     4130.0
Name: total_sale, Length: 2000, dtype: float64

In [28]:
df2['CLV'] = df2.groupby('customer_id')['total_sale'].transform('sum')
df2.head()

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantiy,price_per_unit,cogs,total_sale,value_status,customer_total,clv,CLV
0,180,2022-11-05,10:47:00,117,Male,41.0,Clothing,3.0,300.0,129.0,900.0,Low Value,5200.0,5200.0,5200.0
1,522,2022-07-09,11:00:00,52,Male,46.0,Beauty,3.0,500.0,145.0,1500.0,High Value,10325.0,10325.0,10325.0
2,559,2022-12-12,10:48:00,5,Female,40.0,Clothing,4.0,300.0,84.0,1200.0,High Value,30405.0,30405.0,30405.0
3,1180,2022-01-06,08:53:00,85,Male,41.0,Clothing,3.0,300.0,129.0,900.0,Low Value,8590.0,8590.0,8590.0
4,1522,2022-11-14,08:35:00,48,Male,46.0,Beauty,3.0,500.0,235.0,1500.0,High Value,5870.0,5870.0,5870.0

#### 2. Purchase Frequency

#### 👉 Create a column:

#### Number of purchases per customer

#### Then classify:

#### "Frequent Buyer" (>10 purchases)
#### "Occasional Buyer"

In [39]:
df2['purchase_freq'] = df2.groupby('customer_id')['transactions_id'].transform('count')

In [37]:
df2.drop('CLV', axis=1, inplace=True)
df2

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantiy,price_per_unit,cogs,total_sale,value_status,customer_total,purchase_freq
0,180,2022-11-05,10:47:00,117,Male,41.0,Clothing,3.0,300.0,129.0,900.0,Low Value,5200.0,10
1,522,2022-07-09,11:00:00,52,Male,46.0,Beauty,3.0,500.0,145.0,1500.0,High Value,10325.0,20
2,559,2022-12-12,10:48:00,5,Female,40.0,Clothing,4.0,300.0,84.0,1200.0,High Value,30405.0,63
3,1180,2022-01-06,08:53:00,85,Male,41.0,Clothing,3.0,300.0,129.0,900.0,Low Value,8590.0,22
4,1522,2022-11-14,08:35:00,48,Male,46.0,Beauty,3.0,500.0,235.0,1500.0,High Value,5870.0,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1857,2022-11-09,12:15:00,109,Male,60.0,Electronics,2.0,25.0,7.5,50.0,Low Value,7680.0,18
1996,211,2022-09-12,14:02:00,54,Male,42.0,Beauty,3.0,500.0,235.0,1500.0,High Value,13475.0,21
1997,650,2023-10-08,12:41:00,98,Male,55.0,Electronics,1.0,30.0,15.0,30.0,Low Value,7535.0,14
1998,1211,2023-11-22,14:59:00,82,Male,42.0,Beauty,3.0,500.0,235.0,1500.0,High Value,9360.0,16
1999,1650,2022-09-23,16:24:00,89,Male,55.0,Electronics,1.0,30.0,10.8,30.0,Low Value,4130.0,13

In [42]:

df2['buyer_type'] = df2['purchase_freq'].apply(lambda x: "Frequent Buyer" if x > 10 else "Occasional Buyer")
df2

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantiy,price_per_unit,cogs,total_sale,value_status,customer_total,purchase_freq,buyer_type
0,180,2022-11-05,10:47:00,117,Male,41.0,Clothing,3.0,300.0,129.0,900.0,Low Value,5200.0,10,Occasional Buyer
1,522,2022-07-09,11:00:00,52,Male,46.0,Beauty,3.0,500.0,145.0,1500.0,High Value,10325.0,20,Frequent Buyer
2,559,2022-12-12,10:48:00,5,Female,40.0,Clothing,4.0,300.0,84.0,1200.0,High Value,30405.0,63,Frequent Buyer
3,1180,2022-01-06,08:53:00,85,Male,41.0,Clothing,3.0,300.0,129.0,900.0,Low Value,8590.0,22,Frequent Buyer
4,1522,2022-11-14,08:35:00,48,Male,46.0,Beauty,3.0,500.0,235.0,1500.0,High Value,5870.0,8,Occasional Buyer
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1857,2022-11-09,12:15:00,109,Male,60.0,Electronics,2.0,25.0,7.5,50.0,Low Value,7680.0,18,Frequent Buyer
1996,211,2022-09-12,14:02:00,54,Male,42.0,Beauty,3.0,500.0,235.0,1500.0,High Value,13475.0,21,Frequent Buyer
1997,650,2023-10-08,12:41:00,98,Male,55.0,Electronics,1.0,30.0,15.0,30.0,Low Value,7535.0,14,Frequent Buyer
1998,1211,2023-11-22,14:59:00,82,Male,42.0,Beauty,3.0,500.0,235.0,1500.0,High Value,9360.0,16,Frequent Buyer
1999,1650,2022-09-23,16:24:00,89,Male,55.0,Electronics,1.0,30.0,10.8,30.0,Low Value,4130.0,13,Frequent Buyer

#### Average Order Value (AOV)

#### 👉 For each customer:

#### Compute average spending per transaction

In [45]:
df2['AOV'] = df2['customer_total'] / df2['purchase_freq']
df2

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantiy,price_per_unit,cogs,total_sale,value_status,customer_total,purchase_freq,buyer_type,AOV
0,180,2022-11-05,10:47:00,117,Male,41.0,Clothing,3.0,300.0,129.0,900.0,Low Value,5200.0,10,Occasional Buyer,520.000000
1,522,2022-07-09,11:00:00,52,Male,46.0,Beauty,3.0,500.0,145.0,1500.0,High Value,10325.0,20,Frequent Buyer,516.250000
2,559,2022-12-12,10:48:00,5,Female,40.0,Clothing,4.0,300.0,84.0,1200.0,High Value,30405.0,63,Frequent Buyer,482.619048
3,1180,2022-01-06,08:53:00,85,Male,41.0,Clothing,3.0,300.0,129.0,900.0,Low Value,8590.0,22,Frequent Buyer,390.454545
4,1522,2022-11-14,08:35:00,48,Male,46.0,Beauty,3.0,500.0,235.0,1500.0,High Value,5870.0,8,Occasional Buyer,733.750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1857,2022-11-09,12:15:00,109,Male,60.0,Electronics,2.0,25.0,7.5,50.0,Low Value,7680.0,18,Frequent Buyer,426.666667
1996,211,2022-09-12,14:02:00,54,Male,42.0,Beauty,3.0,500.0,235.0,1500.0,High Value,13475.0,21,Frequent Buyer,641.666667
1997,650,2023-10-08,12:41:00,98,Male,55.0,Electronics,1.0,30.0,15.0,30.0,Low Value,7535.0,14,Frequent Buyer,538.214286
1998,1211,2023-11-22,14:59:00,82,Male,42.0,Beauty,3.0,500.0,235.0,1500.0,High Value,9360.0,16,Frequent Buyer,585.000000
1999,1650,2022-09-23,16:24:00,89,Male,55.0,Electronics,1.0,30.0,10.8,30.0,Low Value,4130.0,13,Frequent Buyer,317.692308

In [46]:
df2['AOV'] = df2.groupby('customer_id')['total_sale'].transform('mean')
df2

,transactions_id,sale_date,sale_time,customer_id,gender,age,category,quantiy,price_per_unit,cogs,total_sale,value_status,customer_total,purchase_freq,buyer_type,AOV
0,180,2022-11-05,10:47:00,117,Male,41.0,Clothing,3.0,300.0,129.0,900.0,Low Value,5200.0,10,Occasional Buyer,520.000000
1,522,2022-07-09,11:00:00,52,Male,46.0,Beauty,3.0,500.0,145.0,1500.0,High Value,10325.0,20,Frequent Buyer,516.250000
2,559,2022-12-12,10:48:00,5,Female,40.0,Clothing,4.0,300.0,84.0,1200.0,High Value,30405.0,63,Frequent Buyer,482.619048
3,1180,2022-01-06,08:53:00,85,Male,41.0,Clothing,3.0,300.0,129.0,900.0,Low Value,8590.0,22,Frequent Buyer,390.454545
4,1522,2022-11-14,08:35:00,48,Male,46.0,Beauty,3.0,500.0,235.0,1500.0,High Value,5870.0,8,Occasional Buyer,733.750000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1857,2022-11-09,12:15:00,109,Male,60.0,Electronics,2.0,25.0,7.5,50.0,Low Value,7680.0,18,Frequent Buyer,426.666667
1996,211,2022-09-12,14:02:00,54,Male,42.0,Beauty,3.0,500.0,235.0,1500.0,High Value,13475.0,21,Frequent Buyer,641.666667
1997,650,2023-10-08,12:41:00,98,Male,55.0,Electronics,1.0,30.0,15.0,30.0,Low Value,7535.0,14,Frequent Buyer,538.214286
1998,1211,2023-11-22,14:59:00,82,Male,42.0,Beauty,3.0,500.0,235.0,1500.0,High Value,9360.0,16,Frequent Buyer,585.000000
1999,1650,2022-09-23,16:24:00,89,Male,55.0,Electronics,1.0,30.0,10.8,30.0,Low Value,4130.0,13,Frequent Buyer,317.692308